/**
 * *************************************************
 * Copyright (c) 2020, Grindrod Bank Limited
 * License MIT: https://opensource.org/licenses/MIT
 * **************************************************
 */
/*
 * A3S
 *
 * API Definition for A3S. This service allows authentication, authorisation and accounting.
 *
 * The version of the OpenAPI document: 2.0.0-alpha-1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using za.co.grindrodbank.a3s.Converters;

namespace za.co.grindrodbank.a3s.A3SApiResources
{ 
    /// <summary>
    /// Represents a transient state of an LDAP authentication mode. 
    /// </summary>
    [DataContract]
    public partial class LdapAuthenticationModeTransient : IEquatable<LdapAuthenticationModeTransient>
    { 
        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public Guid Uuid { get; set; }

        /// <summary>
        /// Gets or Sets LdapAuthenticationModeId
        /// </summary>
        [DataMember(Name="LdapAuthenticationModeId", EmitDefaultValue=false)]
        public Guid LdapAuthenticationModeId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Hostname
        /// </summary>
        [DataMember(Name="hostname", EmitDefaultValue=false)]
        public string Hostname { get; set; }

        /// <summary>
        /// Gets or Sets Port
        /// </summary>
        [DataMember(Name="port", EmitDefaultValue=false)]
        public int Port { get; set; }

        /// <summary>
        /// Gets or Sets IsLdaps
        /// </summary>
        [DataMember(Name="isLdaps", EmitDefaultValue=true)]
        public bool IsLdaps { get; set; }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [DataMember(Name="account", EmitDefaultValue=false)]
        public string Account { get; set; }

        /// <summary>
        /// Gets or Sets BaseDn
        /// </summary>
        [DataMember(Name="baseDn", EmitDefaultValue=false)]
        public string BaseDn { get; set; }

        /// <summary>
        /// A boolean flag indicating whether the password has changed.
        /// </summary>
        /// <value>A boolean flag indicating whether the password has changed.</value>
        [DataMember(Name="password", EmitDefaultValue=true)]
        public bool Password { get; set; }

        /// <summary>
        /// A list of LDAP attribute to user field mappings.
        /// </summary>
        /// <value>A list of LDAP attribute to user field mappings.</value>
        [DataMember(Name="ldapAttributes", EmitDefaultValue=false)]
        public List<LdapAttributeLink> LdapAttributes { get; set; }

        /// <summary>
        /// Gets or Sets RState
        /// </summary>
        [DataMember(Name="r_state", EmitDefaultValue=false)]
        public string RState { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public string Action { get; set; }

        /// <summary>
        /// The current approval count.
        /// </summary>
        /// <value>The current approval count.</value>
        [DataMember(Name="approvalCount", EmitDefaultValue=false)]
        public int ApprovalCount { get; set; }

        /// <summary>
        /// The required approval count before this entity is released.
        /// </summary>
        /// <value>The required approval count before this entity is released.</value>
        [DataMember(Name="requiredApprovalCount", EmitDefaultValue=false)]
        public int RequiredApprovalCount { get; set; }

        /// <summary>
        /// The UUID of the user who created this transient state record.
        /// </summary>
        /// <value>The UUID of the user who created this transient state record.</value>
        [DataMember(Name="createdBy", EmitDefaultValue=false)]
        public Guid CreatedBy { get; set; }

        /// <summary>
        /// The date that this transient state was created.
        /// </summary>
        /// <value>The date that this transient state was created.</value>
        [DataMember(Name="createdAt", EmitDefaultValue=false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LdapAuthenticationModeTransient {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  LdapAuthenticationModeId: ").Append(LdapAuthenticationModeId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Hostname: ").Append(Hostname).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  IsLdaps: ").Append(IsLdaps).Append("\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  BaseDn: ").Append(BaseDn).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  LdapAttributes: ").Append(LdapAttributes).Append("\n");
            sb.Append("  RState: ").Append(RState).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  ApprovalCount: ").Append(ApprovalCount).Append("\n");
            sb.Append("  RequiredApprovalCount: ").Append(RequiredApprovalCount).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((LdapAuthenticationModeTransient)obj);
        }

        /// <summary>
        /// Returns true if LdapAuthenticationModeTransient instances are equal
        /// </summary>
        /// <param name="other">Instance of LdapAuthenticationModeTransient to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LdapAuthenticationModeTransient other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Uuid == other.Uuid ||
                    Uuid != null &&
                    Uuid.Equals(other.Uuid)
                ) && 
                (
                    LdapAuthenticationModeId == other.LdapAuthenticationModeId ||
                    LdapAuthenticationModeId != null &&
                    LdapAuthenticationModeId.Equals(other.LdapAuthenticationModeId)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Hostname == other.Hostname ||
                    Hostname != null &&
                    Hostname.Equals(other.Hostname)
                ) && 
                (
                    Port == other.Port ||
                    
                    Port.Equals(other.Port)
                ) && 
                (
                    IsLdaps == other.IsLdaps ||
                    
                    IsLdaps.Equals(other.IsLdaps)
                ) && 
                (
                    Account == other.Account ||
                    Account != null &&
                    Account.Equals(other.Account)
                ) && 
                (
                    BaseDn == other.BaseDn ||
                    BaseDn != null &&
                    BaseDn.Equals(other.BaseDn)
                ) && 
                (
                    Password == other.Password ||
                    
                    Password.Equals(other.Password)
                ) && 
                (
                    LdapAttributes == other.LdapAttributes ||
                    LdapAttributes != null &&
                    other.LdapAttributes != null &&
                    LdapAttributes.SequenceEqual(other.LdapAttributes)
                ) && 
                (
                    RState == other.RState ||
                    RState != null &&
                    RState.Equals(other.RState)
                ) && 
                (
                    Action == other.Action ||
                    Action != null &&
                    Action.Equals(other.Action)
                ) && 
                (
                    ApprovalCount == other.ApprovalCount ||
                    
                    ApprovalCount.Equals(other.ApprovalCount)
                ) && 
                (
                    RequiredApprovalCount == other.RequiredApprovalCount ||
                    
                    RequiredApprovalCount.Equals(other.RequiredApprovalCount)
                ) && 
                (
                    CreatedBy == other.CreatedBy ||
                    CreatedBy != null &&
                    CreatedBy.Equals(other.CreatedBy)
                ) && 
                (
                    CreatedAt == other.CreatedAt ||
                    CreatedAt != null &&
                    CreatedAt.Equals(other.CreatedAt)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Uuid != null)
                    hashCode = hashCode * 59 + Uuid.GetHashCode();
                    if (LdapAuthenticationModeId != null)
                    hashCode = hashCode * 59 + LdapAuthenticationModeId.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Hostname != null)
                    hashCode = hashCode * 59 + Hostname.GetHashCode();
                    
                    hashCode = hashCode * 59 + Port.GetHashCode();
                    
                    hashCode = hashCode * 59 + IsLdaps.GetHashCode();
                    if (Account != null)
                    hashCode = hashCode * 59 + Account.GetHashCode();
                    if (BaseDn != null)
                    hashCode = hashCode * 59 + BaseDn.GetHashCode();
                    
                    hashCode = hashCode * 59 + Password.GetHashCode();
                    if (LdapAttributes != null)
                    hashCode = hashCode * 59 + LdapAttributes.GetHashCode();
                    if (RState != null)
                    hashCode = hashCode * 59 + RState.GetHashCode();
                    if (Action != null)
                    hashCode = hashCode * 59 + Action.GetHashCode();
                    
                    hashCode = hashCode * 59 + ApprovalCount.GetHashCode();
                    
                    hashCode = hashCode * 59 + RequiredApprovalCount.GetHashCode();
                    if (CreatedBy != null)
                    hashCode = hashCode * 59 + CreatedBy.GetHashCode();
                    if (CreatedAt != null)
                    hashCode = hashCode * 59 + CreatedAt.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(LdapAuthenticationModeTransient left, LdapAuthenticationModeTransient right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(LdapAuthenticationModeTransient left, LdapAuthenticationModeTransient right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
