/**
 * *************************************************
 * Copyright (c) 2020, Grindrod Bank Limited
 * License MIT: https://opensource.org/licenses/MIT
 * **************************************************
 */
/*
 * A3S
 *
 * API Definition for A3S. This service allows authentication, authorisation and accounting.
 *
 * The version of the OpenAPI document: 1.1.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using za.co.grindrodbank.a3s.Converters;

namespace za.co.grindrodbank.a3s.A3SApiResources
{ 
    /// <summary>
    /// Represents a collection of all the latest transients for teams with any changes. 
    /// </summary>
    [DataContract]
    public partial class SystemTransientsTeam : IEquatable<SystemTransientsTeam>
    { 
        /// <summary>
        /// Gets or Sets Uuid
        /// </summary>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public Guid Uuid { get; set; }

        /// <summary>
        /// Gets or Sets TeamName
        /// </summary>
        [DataMember(Name="teamName", EmitDefaultValue=false)]
        public string TeamName { get; set; }

        /// <summary>
        /// Gets or Sets CapturerUuid
        /// </summary>
        [DataMember(Name="capturerUuid", EmitDefaultValue=false)]
        public Guid CapturerUuid { get; set; }

        /// <summary>
        /// Gets or Sets CapturerName
        /// </summary>
        [DataMember(Name="capturerName", EmitDefaultValue=false)]
        public string CapturerName { get; set; }

        /// <summary>
        /// Gets or Sets CapturedDate
        /// </summary>
        [DataMember(Name="capturedDate", EmitDefaultValue=false)]
        public DateTime CapturedDate { get; set; }

        /// <summary>
        /// Gets or Sets LatestActiveTeamTransient
        /// </summary>
        [DataMember(Name="latestActiveTeamTransient", EmitDefaultValue=false)]
        public TeamBaseTeamTransient LatestActiveTeamTransient { get; set; }

        /// <summary>
        /// A list of the latest (most recent one per relation) transient team - data policy assignment changes for this transient role.
        /// </summary>
        /// <value>A list of the latest (most recent one per relation) transient team - data policy assignment changes for this transient role.</value>
        [DataMember(Name="latestTransientTeamDataPolicies", EmitDefaultValue=false)]
        public List<TeamDataPolicyTransient> LatestTransientTeamDataPolicies { get; set; }

        /// <summary>
        /// A list of the latest (most recent one per relation) transient team - child team assignment changes for this transient role.
        /// </summary>
        /// <value>A list of the latest (most recent one per relation) transient team - child team assignment changes for this transient role.</value>
        [DataMember(Name="latestTransientTeamChildTeams", EmitDefaultValue=false)]
        public List<TeamChildTeamTransient> LatestTransientTeamChildTeams { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SystemTransientsTeam {\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  TeamName: ").Append(TeamName).Append("\n");
            sb.Append("  CapturerUuid: ").Append(CapturerUuid).Append("\n");
            sb.Append("  CapturerName: ").Append(CapturerName).Append("\n");
            sb.Append("  CapturedDate: ").Append(CapturedDate).Append("\n");
            sb.Append("  LatestActiveTeamTransient: ").Append(LatestActiveTeamTransient).Append("\n");
            sb.Append("  LatestTransientTeamDataPolicies: ").Append(LatestTransientTeamDataPolicies).Append("\n");
            sb.Append("  LatestTransientTeamChildTeams: ").Append(LatestTransientTeamChildTeams).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SystemTransientsTeam)obj);
        }

        /// <summary>
        /// Returns true if SystemTransientsTeam instances are equal
        /// </summary>
        /// <param name="other">Instance of SystemTransientsTeam to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SystemTransientsTeam other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Uuid == other.Uuid ||
                    Uuid != null &&
                    Uuid.Equals(other.Uuid)
                ) && 
                (
                    TeamName == other.TeamName ||
                    TeamName != null &&
                    TeamName.Equals(other.TeamName)
                ) && 
                (
                    CapturerUuid == other.CapturerUuid ||
                    CapturerUuid != null &&
                    CapturerUuid.Equals(other.CapturerUuid)
                ) && 
                (
                    CapturerName == other.CapturerName ||
                    CapturerName != null &&
                    CapturerName.Equals(other.CapturerName)
                ) && 
                (
                    CapturedDate == other.CapturedDate ||
                    CapturedDate != null &&
                    CapturedDate.Equals(other.CapturedDate)
                ) && 
                (
                    LatestActiveTeamTransient == other.LatestActiveTeamTransient ||
                    LatestActiveTeamTransient != null &&
                    LatestActiveTeamTransient.Equals(other.LatestActiveTeamTransient)
                ) && 
                (
                    LatestTransientTeamDataPolicies == other.LatestTransientTeamDataPolicies ||
                    LatestTransientTeamDataPolicies != null &&
                    other.LatestTransientTeamDataPolicies != null &&
                    LatestTransientTeamDataPolicies.SequenceEqual(other.LatestTransientTeamDataPolicies)
                ) && 
                (
                    LatestTransientTeamChildTeams == other.LatestTransientTeamChildTeams ||
                    LatestTransientTeamChildTeams != null &&
                    other.LatestTransientTeamChildTeams != null &&
                    LatestTransientTeamChildTeams.SequenceEqual(other.LatestTransientTeamChildTeams)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Uuid != null)
                    hashCode = hashCode * 59 + Uuid.GetHashCode();
                    if (TeamName != null)
                    hashCode = hashCode * 59 + TeamName.GetHashCode();
                    if (CapturerUuid != null)
                    hashCode = hashCode * 59 + CapturerUuid.GetHashCode();
                    if (CapturerName != null)
                    hashCode = hashCode * 59 + CapturerName.GetHashCode();
                    if (CapturedDate != null)
                    hashCode = hashCode * 59 + CapturedDate.GetHashCode();
                    if (LatestActiveTeamTransient != null)
                    hashCode = hashCode * 59 + LatestActiveTeamTransient.GetHashCode();
                    if (LatestTransientTeamDataPolicies != null)
                    hashCode = hashCode * 59 + LatestTransientTeamDataPolicies.GetHashCode();
                    if (LatestTransientTeamChildTeams != null)
                    hashCode = hashCode * 59 + LatestTransientTeamChildTeams.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SystemTransientsTeam left, SystemTransientsTeam right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SystemTransientsTeam left, SystemTransientsTeam right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
