/**
 * *************************************************
 * Copyright (c) 2020, Grindrod Bank Limited
 * License MIT: https://opensource.org/licenses/MIT
 * **************************************************
 */
/*
 * A3S
 *
 * API Definition for A3S. This service allows authentication, authorisation and accounting.
 *
 * The version of the OpenAPI document: 2.0.0-alpha-1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using za.co.grindrodbank.a3s.Converters;

namespace za.co.grindrodbank.a3s.A3SApiResources
{ 
    /// <summary>
    /// Represents the current active transients for a terms of service agreement. 
    /// </summary>
    [DataContract]
    public partial class TermsOfServiceTransients : IEquatable<TermsOfServiceTransients>
    { 
        /// <summary>
        /// Gets or Sets LatestActiveTermsOfServiceTransients
        /// </summary>
        [DataMember(Name="latestActiveTermsOfServiceTransients", EmitDefaultValue=false)]
        public List<TermsOfServiceTransient> LatestActiveTermsOfServiceTransients { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TermsOfServiceTransients {\n");
            sb.Append("  LatestActiveTermsOfServiceTransients: ").Append(LatestActiveTermsOfServiceTransients).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((TermsOfServiceTransients)obj);
        }

        /// <summary>
        /// Returns true if TermsOfServiceTransients instances are equal
        /// </summary>
        /// <param name="other">Instance of TermsOfServiceTransients to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TermsOfServiceTransients other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    LatestActiveTermsOfServiceTransients == other.LatestActiveTermsOfServiceTransients ||
                    LatestActiveTermsOfServiceTransients != null &&
                    other.LatestActiveTermsOfServiceTransients != null &&
                    LatestActiveTermsOfServiceTransients.SequenceEqual(other.LatestActiveTermsOfServiceTransients)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (LatestActiveTermsOfServiceTransients != null)
                    hashCode = hashCode * 59 + LatestActiveTermsOfServiceTransients.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(TermsOfServiceTransients left, TermsOfServiceTransients right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(TermsOfServiceTransients left, TermsOfServiceTransients right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
