/**
 * *************************************************
 * Copyright (c) 2020, Grindrod Bank Limited
 * License MIT: https://opensource.org/licenses/MIT
 * **************************************************
 */
/*
 * A3S
 *
 * API Definition for A3S. This service allows authentication, authorisation and accounting.
 *
 * The version of the OpenAPI document: 2.0.0-alpha-1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using za.co.grindrodbank.a3s.Attributes;
using Microsoft.AspNetCore.Authorization;
using za.co.grindrodbank.a3s.A3SApiResources;

namespace za.co.grindrodbank.a3s.AbstractApiControllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class TransientsApiController : ControllerBase
    { 
        /// <summary>
        /// Gets a list of all the entities that are currently being changed within the system.
        /// </summary>
        /// <remarks>Gets a list of all the entities that are currently being changed within the system. The requested entity types can be filtered with query params.</remarks>
        /// <param name="page">The page to view.</param>
        /// <param name="size">The size of a page.</param>
        /// <param name="includeRoles">A flag controlling whether to include all role type records within the returned response.</param>
        /// <param name="includeFunctions">A flag controlling whether to include all function type records within the returned response.</param>
        /// <param name="includeAuthModes">A flag controlling whether to include all authentication model type records within the returned response.</param>
        /// <param name="includeUsers">A flag controlling whether to include all user type records within the returned response.</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad Request.</response>
        /// <response code="401">Not authenticated.</response>
        /// <response code="403">Forbidden - You are not authorized to read Sub-Realms.</response>
        /// <response code="404">Sub-Realm not found.</response>
        /// <response code="500">An unexpected error occurred.</response>
        [HttpGet]
        [Route("/transients", Name = "GetTransients")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(SystemTransients))]
        [ProducesResponseType(statusCode: 400, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 401, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 403, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 404, type: typeof(ErrorResponse))]
        [ProducesResponseType(statusCode: 500, type: typeof(ErrorResponse))]
        public abstract Task<IActionResult> GetTransientsAsync([FromQuery]int page, [FromQuery][Range(1, 1000)]int size, [FromQuery]bool includeRoles, [FromQuery]bool includeFunctions, [FromQuery]bool includeAuthModes, [FromQuery]bool includeUsers);
    }
}
